language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm run build
  - npm run export

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target_branch: master
  local_dir: dist
  on:
    branch: gh-pages
