os: linux
language: ruby
rvm:
  - 2.5.1

cache: bundler

branches:
  only:
  - gh-pages

before_script:
  - chmod +x ./scripts/travis_build

script: ./scripts/travis_build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target_branch: master
  local_dir: _site
  on:
    branch: gh-pages
